## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'import Pkg; Pkg.clone(pwd()); Pkg.build("REDCap")' #; Pkg.test("REDCap"; coverage=true)'
#- julia -e 'if VERSION < v"0.7.0-DEV.5183"; Pkg.clone(pwd()); Pkg.build("REDCap"); else using Pkg; Pkg.build(); end'
#- julia -e 'if VERSION < v\"0.7.0-DEV.5183\"; Pkg.add("Test"); Pkg.test("REDCap", coverage=true); else using Pkg; Pkg.add("Test"); Pkg.test(coverage=true); end'
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("REDCap")); Pkg.add("Documenter"); Pkg.add("Literate"); include(joinpath("docs", "make.jl"))'
  # push coverage results to Coveralls
  #- julia -e 'using Pkg; cd(Pkg.dir("REDCap")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  #- julia -e 'using Pkg; cd(Pkg.dir("REDCap")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'




