""" importEvents(config::Config, userData; format::String="json", override::Int=0, returnFormat::String="json") 

This method allows you to import Events into a project or to update 
existing Events' attributes, such as the event name, days offset, etc. 
The unique event name of an Event cannot be changed because it is 
auto-generated by REDCap. Please note that the only way to update an 
existing Event is to provide the unique_event_name attribute, and if 
the unique_event_name attribute is missing for an Event being imported 
(when override=0), it will assume it to be a new Event that should be 
created. Notice: Because of the 'override' parameter's destructive 
nature, this method may only use override=1 for projects in Development 
status.

NOTE: This only works for longitudinal projects. """
###############NOT IMPLEMENTED/BROKEN###############
function importEvents(config::Config, userData; format::String="json", override::Int=0, returnFormat::String="json")
	
	fields = Dict("token" => config.key, 
				  "content" => "event", 
				  "format" => format,
				  "data" => data,
				  "action" => "import",
				  "override" => override,
				  "returnFormat" => returnFormat)

	print("POSTing")
	output = HTTP.post(config.url; body=fields)
	print("POSTd")
	return JSON.parse(String(output.body))
end